nwa ci test

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -27,4 +27,13 @@ jobs:
         run: go install github.com/B1NARY-GR0UP/nwa@37adc510599dfca423289f9683f3d10a9db766eb
 
       - name: Run License Header Check
+        id: license_check
         run: nwa check -c "BINARY Members" -l apache -y 2024 ./*.go
+
+      - name: Check License Header Results
+        run: |
+          mismatched_count=$(nwa check -c "BINARY Members" -l apache -y 2024 ./*.go | grep -o 'mismatched=[0-9]*' | cut -d'=' -f2)
+          if [ "$mismatched_count" -ne 0 ]; then
+            echo "License header check failed: some files are missing the correct license header."
+            exit 1
+          fi
